language: php

php:
  - 5.6
  - 7.0

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

install: travis_retry composer install --no-interaction

script:
    "phpunit --coverage-text --coverage-clover build/logs/clover.xml"
